 - hosts: db
   become: true
   vars:
     mysql_root_password: mdp
   tasks:
    - name: Install MYSQL
      dnf:
        name: mariadb-server
        state: present
    # - name: Install the Python MySQL Support Libraries
    #   dnf: pkg=MySQL-python state=latest
    - name: start mysql server and enable it on reboot
      service: 
        name: mariadb 
        state: started 
        enabled: true

    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost

    # - name: Create a New Test DB called MyNewDB
    #   mysql_db: name=MyNewDB state=present login_user=root login_password={{ mysql_root_password }}