- hosts: db
  become: true
  tasks:
  - name: Installing php
    dnf:
      name:
        - php
        - php-common
        - php-cli
        - php-gd
        - php-curl
        - php-mysqlnd
        - php-fpm
        - php-mysqli
        - php-pdo
      state: latest