- hosts: web
  become: true
  tasks:

  - name: Install APACHE latest
    dnf:
      name: httpd
      state: latest

  - name: Start APACHE
    service:
      name: httpd
      state: started

  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: true
      state: enabled

  - name: Restart apache service
    service:
      name: "{{ item }}"
      state: restarted
      enable: true
    loop:
      - nginx
      - firewalld