 - hosts: db
   become: true
   vars:
     mysql_root_password: mdp
   
   tasks:
    - name: Install MYSQL
      dnf:
        name: 
          - mariadb-server
          - python3-PyMySQL
        state: present
        
    - name: start mysql server and enable it on reboot
      service: 
        name: mariadb 
        state: started 
        enabled: true

    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
        password: "{{ mysql_root_password }}"
        host: localhost

    - name: Allow external MySQL connexions (1/2)
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        regexp: '^skip-external-locking'
        line: "# skip-external-locking"
      notify: Restart mariadb

    - name: Allow external MySQL connexions (2/2)
      lineinfile:
        path: /etc/my.cnf.d/mariadb-server.cnf
        regexp: '^bind-address'
        line: "# bind-address"
      notify: Restart mariadb

      handlers:
      - name: Restart mariadb
        service:
          name: mariadb
          state: restarted
    # - name: Create a New Test DB called MyNewDB
    #   mysql_db: name=MyNewDB state=present login_user=root login_password={{ mysql_root_password }}