- hosts: web
  become: true
  tasks:

  - name: Install APACHE latest
    dnf:
      name: httpd
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Start APACHE
    service:
      name: httpd
      state: started

  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: true
      state: enabled

  - name: Restart apache service
    service:
      name: "{{ item }}"
      state: restarted
    loop:
      - httpd
      - firewalld

  - name: Give writable mode to http folder
    file:
      path: /var/www/html
      state: directory
      mode: '0755'

  - name: remove default index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: upload web app source
    copy:
      src: app/
      dest: /var/www/html/