- hosts: web
  become: yes
  tasks:
  - name: Install APACHE latest
    dnf:
      name: httpd
      state: latest
  - name: Start APACHE
    service:
      name: httpd
      state: started
  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled
  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted