# - hosts: minikube
#   become: true
#   tasks:

#   - name: Remote RPM install with yum
#     shell: |
#       sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#       sudo dnf install -y --allowerasing docker-ce
#       sudo systemctl enable --now docker
#       sudo usermod -aG docker $USER && newgrp docker
#       curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
#       sudo install minikube-linux-amd64 /usr/local/bin/minikube
#       alias kubectl="minikube kubectl --"
#       minikube config set driver docker
#       minikube start



- name: install Docker
  hosts: minikube
  become: true
  tasks:

    - name: Add signing key
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/{{ mydistribution }}/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/{{ mydistribution }}/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started