- hosts: minikube
  become: true
  tasks:

  - name: Remote RPM install with yum
    shell: |
      sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
      sudo dnf install -y --allowerasing docker-ce
      sudo systemctl enable --now docker
      sudo usermod -aG docker $USER
      newgrp docker

# curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
# sudo rpm -Uvh minikube-latest.x86_64.rpm